
GET http://localhost:3000/contacts

###

GET http://localhost:3000/contacts/626b3634e37f6a6b1d770bfb

###

GET https://cse341node-lyonr.herokuapp.com/contacts

###

GET https://cse341node-lyonr.herokuapp.com/contacts/626b3634e37f6a6b1d770bfb
